/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndkdemo_binea_com_ndkdemo_MainActivity */

#ifndef _Included_ndkdemo_binea_com_ndkdemo_MainActivity
#define _Included_ndkdemo_binea_com_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndkdemo_binea_com_ndkdemo_MainActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndkdemo_binea_com_ndkdemo_MainActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
